name: Generate Json Debug

on:
  workflow_dispatch:
  
concurrency:
  group: generate-json-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: FedericoCarboni/setup-ffmpeg@v3
      - name: initialize git setting.
        run: |
          git config user.name "iranika"
          git config user.email "7370486+iranika@users.noreply.github.com"
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v4
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-psmodules-anglparse
      - name: install module
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module AngleParse
      - name: generate-webp
        run: |
          pwsh ./mops/update-json.ps1 -Debug
