name: feed file updated
on:
  workflow_dispatch:

  push:
    paths:
      - 'feed.atom'
jobs:
  feed-file-updated:
    strategy:
      matrix:
        repo: ['iranika/mo-4koma']
    name: feed-file-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch feed-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: feed-updated
