name: feed file updated
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/feed.atom'

concurrency:
  group: push-feed-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  feed-file-updated:
    strategy:
      matrix:
        repo: ['iranika/mo-4koma']
    name: feed-file-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch feed-updated
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: feed-updated
